### ISSUE TITLE
Filters incomplete

### ISSUE THREAD

**Issue by GilesS420** [TomeIDK/Programming-Project#19]
filters moeten nog een correcte functionaliteit krijgen

temp. lijst toevoegen om de functionaliteiten te testen
zorgen dat de lijst zichtbaar is 
kunnen toevoegen en verwijderen van de filters

(Datalist kan amper gestyled worden in css, beter een normale lijst gebruiken om een mooier resultaat te krijgen.)

**Comment by TomeIDK** [comment]
Filter voor tags klaar, zelfde voor zoekbalk. Gewoon nog linken aan de data dat gefilterd moet worden voor beiden
